version: 2

project_name: cursor-utils-installer

before:
  hooks:
    - go mod tidy
    - cp ../LICENSE LICENSE

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    main: ./cmd/cursor-utils
    binary: cursor-utils
    ldflags:
      - -s -w -X github.com/imflawlezz/cursor-utils/installer/internal/config.Version={{ .Version }}

archives:
  - formats:
      - tar.gz
    format_overrides:
      - goos: windows
        formats:
          - zip
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    files:
      - LICENSE
      - README.md

checksum:
  name_template: checksums.txt

changelog:
  disable: true

release:
  draft: false
  replace_existing_draft: true
  mode: replace
